### ISSUE TITLE
Problem with usage of the translation tables.

### ISSUE THREAD

**Issue by Setahero** [sbsdev/sbs-braille-tables#14]
I am currently trying to use your tables for a student project, which involves brailletranslations from german to braille for a rendering process for diagrams. 
The liblois integration is done (the java implementation) and i can parse your tables without errors from liblouis. But unfortunately, i cant seem to get anything usefull from the tables. Either i get a empty string, or i get for example for an "A" (uppercase) an "a" without the needed uppercase sign ($). 

Could you please add a little "How to use" example, so i could see how to decide. which  translation table is the right one? For now, i am "bruteforcing" the correct table via changing includes, which is of course not how it should be done.

**Comment by egli** [comment]
Interesting. What kind of a student project are you working on?

We produce fairly advanced braille in that we tag names, places, abbrevs, etc in the source code. We then use some [xsl magic](https://github.com/sbsdev/dtbook2sbsform/blob/master/xsl/dtbook2sbsform.xsl#L284) to use the correct tables depending on the context. If your source doesn't have that level, then you'd be way better of to just use the German braille tables that are shipped with liblouis. We have pushed most of our tables upstream not too long ago.

Ask me on the mailing list if you have more questions
